#ifndef DNAEDITORDIALOG_H
#define DNAEDITORDIALOG_H

#include <QDialog>
#include <QVector>

class QComboBox;
class QSlider;
class QSpinBox;
class QDoubleSpinBox;
class QCheckBox;
class QLabel;
class SpectrumVisualizer;

/**
 * DNA Editor Dialog - Simple editor for harmonic distribution patterns
 *
 * Simplified version focusing on core functionality:
 * - Sequence dropdown (All, Odd, Even, OddDominant, Fundamental+, Octaves, Custom)
 * - Purity slider (0-100%)
 * - Spectrum preview
 * - OK/Cancel buttons
 */
class DnaEditorDialog : public QDialog
{
    Q_OBJECT

public:
    explicit DnaEditorDialog(int numHarmonics = 64, QWidget *parent = nullptr);
    ~DnaEditorDialog();

    // Get custom DNA pattern generated by the dialog
    QVector<double> getCustomDnaPattern() const { return customPattern; }

    // Get the name of the loaded DNA (filename if loaded from file, empty otherwise)
    QString getLoadedName() const { return loadedName; }

    // Digit formula mode queries
    bool isDigitFormulaMode() const;
    QString getComputedDigitString(int needed = 1000) const;
    int getFormulaStartDigit() const;

    // Set an existing custom pattern (for editing existing custom DNA)
    void setCustomPattern(const QVector<double> &pattern);

private slots:
    void onSequenceChanged(int index);
    void onSaveCustomDna();
    void onLoadCustomDna();

private:
    QComboBox *comboSequence;
    SpectrumVisualizer *spectrumPreview;

    int numHarmonics;
    QVector<double> customPattern;  // Generated harmonic amplitudes
    QString loadedName;  // Name from loaded file

    void updatePattern();
    void generateSequencePattern(int sequenceType);

    // --- Digit Formula ---
    QWidget        *digitFormulaWidget;
    QComboBox      *comboConstantPresets;
    QDoubleSpinBox *spinOperandA;
    QComboBox      *comboOperator;
    QDoubleSpinBox *spinOperandB;
    QLabel         *labelOperandB;
    QSpinBox       *spinStartDigit;
    QCheckBox      *checkNormalize;
    QLabel         *labelResult;

    void   createDigitFormulaWidget();
    void   generateDigitFormulaPattern();
    bool    isRationalFormula() const;
    QString computeFormulaDigits(int needed) const;
    QString extractLongDoubleDigits(long double value) const;
    void   updateDigitResultLabel(const QString &digitStr);
};

#endif // DNAEDITORDIALOG_H
